apiVersion: luizfilho.cloud/v1alpha1
kind: App
metadata:
  name: podinfo
spec:
  source:
    owner: luizbafilho
    repo: podinfo
    branch: master
  replicas: 2
  public: true
  env:
  - name: "PODINFO_PORT"
    value: "8080"
  build:
    dockerfile: Dockerfile.xx
